name = "artisans-ng"
compatibility_date = "2026-05-08"

pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "18"
NEXT_PUBLIC_API_URL = "https://artisans-ojzr.onrender.com/api"
NEXT_PUBLIC_WS_URL = "https://artisans-ojzr.onrender.com"